title: Dominion of Light
theme: jekyll-theme-merlot
show_downloads: true
pc_url: https://github.com/bcolemutech/dol-con/releases/latest/download/dol-pc.zip
mac_url: https://github.com/bcolemutech/dol-con/releases/latest/download/dol-osx.zip
